### ISSUE TITLE
Why there is a `githubUsers` method in api.js?

### ISSUE THREAD

**Issue by lastguest** [michaelgenesini/wordpress-next-client#4]
This code is not used anywhere :
https://github.com/michaelgenesini/wordpress-next-client/blob/master/libs/api.js#L46
Can be removed?

**Comment by michaelgenesini** [comment]
The GitHub API call was an example of an external call (not necessary WordPress) so at the moment I keep it there.
I'm planning a little refactoring so this project can be a plug ad play client for wordpress.
Thanks ;)
